import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import TestContext from "@/Context/TestContext";
import Count from "@/Components/Count/Count";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={`${inter.variable} w-[80%] mx-auto font-in`}>
        {/* <Link href={"/admin/dashboard/add-product"}>
          <button className="btn bg-blue-600 rounded-2xl p-4">
            add product
          </button>
        </Link>
        <Link href={"/"}>
          <button className="btn bg-blue-600 rounded-2xl p-4">home</button>
        </Link>
        {/* <Link href={"/contact"}>
          <button className="btn bg-blue-600 rounded-2xl p-4">contact</button>
        </Link> */}
        <TestContext>
          {/* <Count /> */}
          <h1>sayel</h1>
        </TestContext>
      </body>
    </html>
  );
}
